// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NamesAndTypes.Data;

namespace NamesAndTypes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220306124942_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("NamesAndTypes.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameOfWorker")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NameOfWorker")
                        .IsUnique()
                        .HasFilter("[NameOfWorker] IS NOT NULL");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 771, DateTimeKind.Local).AddTicks(9172),
                            NameOfWorker = "Ivan",
                            Type = "Programmer"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 772, DateTimeKind.Local).AddTicks(6535),
                            NameOfWorker = "Petr",
                            Type = "Builder"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 772, DateTimeKind.Local).AddTicks(6550),
                            NameOfWorker = "Vailiy",
                            Type = "Police"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 772, DateTimeKind.Local).AddTicks(6552),
                            NameOfWorker = "Kolia",
                            Type = "Officer"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 772, DateTimeKind.Local).AddTicks(6554),
                            NameOfWorker = "George",
                            Type = "Medical"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 772, DateTimeKind.Local).AddTicks(6555),
                            NameOfWorker = "Olga",
                            Type = "Worker"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 772, DateTimeKind.Local).AddTicks(6556),
                            NameOfWorker = "Aria",
                            Type = "Programmer"
                        });
                });

            modelBuilder.Entity("NamesAndTypes.Models.WType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 773, DateTimeKind.Local).AddTicks(9889),
                            Type = "Programmer"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 774, DateTimeKind.Local).AddTicks(356),
                            Type = "Builder"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 774, DateTimeKind.Local).AddTicks(361),
                            Type = "Police"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 774, DateTimeKind.Local).AddTicks(362),
                            Type = "Officer"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 774, DateTimeKind.Local).AddTicks(363),
                            Type = "Worker"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 3, 6, 16, 49, 41, 774, DateTimeKind.Local).AddTicks(364),
                            Type = "Medical"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
